build_run_cpp:
	g++ ./cpp/first_missing_positive.cpp -o ./cpp/first_missing_positive.o
	./cpp/first_missing_positive.o

build_run_c:
	gcc ./c/first_missing_positive.c -o ./c/first_missing_positive.o
	./c/first_missing_positive.o

test_go:
	go test ./go/... -v